# Runs a docker container that handles the parsing and reuploading

name: Run Docker

# Controls when the workflow will run
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ fromJSON(inputs.large-runner && '["self-hosted", "Linux", "chunky"]' || '["self-hosted", "Linux"]') }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: docker registry login
      env:
          ORG_DOCKERHUB_TOKEN: ${{ secrets.ORG_DOCKERHUB_TOKEN }}
          ORG_DOCKERHUB_USERNAME: ${{ secrets.ORG_DOCKERHUB_USERNAME }}
      run: echo "$ORG_DOCKERHUB_TOKEN" | docker login -u "$ORG_DOCKERHUB_USERNAME" --password-stdin

    - name: Build and Run Docker Container
      env:
            s3accesskey: ${{ secrets.ACTION_S3_ACCESSKEY }}
            s3base: ${{ secrets.ACTION_S3_BASE }}
            s3bucket: ${{ secrets.ACTION_S3_BUCKET }}
            s3secretkey: ${{ secrets.ACTION_S3_SECRETKEY }}
            gh_token: ${{ secrets.GITHUB_TOKEN }}
      run: |
          docker run --rm -i \
            -e s3accesskey=${{ secrets.ACTION_S3_ACCESSKEY }} \
            -e s3base=${{ secrets.ACTION_S3_BASE }} \
            -e s3bucket=${{ secrets.ACTION_S3_BUCKET }} \
            -e s3secretkey=${{ secrets.ACTION_S3_SECRETKEY }} \
            -e gh_token=${{ secrets.GITHUB_TOKEN }} \
            rexwang8/gutenberg:tres
